#! /bin/sh

sxhkd &

# wallpaper
hsetroot -fill /home/rustam/images/ghostIntTheShell.jpg

# cursor
xsetroot -cursor_name left_ptr

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config click_to_focus	  false
bspc config history_aware_focus   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#131313"
bspc config focused_border_color "#19b898"
bspc config presel_feedback_color "#AD235E"

$HOME/.config/polybar/launch.sh
